actions/starter-workflows

automation/stale.yml

Fix a typo in stale.yml

---

ci/properties/gem-push.properties.json

Was wrapping 3 lines in the UI. Two lines looks nicer FYI @pmarsceill

Shorten gems description

---

ci/c-cpp.yml

make test is a perl'ism (and probably other), autotools use make check.
add make distcheck

Update c-cpp.yml for configure/automake

---

automation/properties/greetings.properties.json

Generated by https://github.com/jsoref/spelling `f`; to maintain your repo, please consider `fchurn`
I'm actually interested in figuring out how to make `fchurn` into an action...

spelling: contributors

---

.github/pull_request_template.md
CODE_OF_CONDUCT.md
CONTRIBUTING.md

👋 This adds in a couple of things to this repo:
* A code of conduct
* A rather more detailed contributing document for all the awesome people working on this
* Guidelines on the pull request on the contribution document so people will know whats accepted on this repository.

Add in guidelines for contributing

---

ci/php.yml
ci/properties/php.properties.json

Added simple PHP starter template along with properties file.
There doesn't seem to be any `actions/setup-php` yet (at least not public), so I skipped a build matrix using several PHP versions.
Resolves #15.

Initial commit of PHP template

---

ci/properties/scala.properties.json
ci/scala.yml

Added simple Scala starter template along with properties file.
Need to find a svg scala logo

Add Scala workflow

---

ci/node.js.yml

https://docs.npmjs.com/cli/ci.html

Use npm ci instead of npm install

---

automation/label.yml

Fix TYPO in the comment block

---

ci/python-package.yml

Thank you for sending in this pull request. Please make sure you take a look at the [contributing file](CONTRIBUTING.md). Here's a few things for you to consider in this pull request:

Add Python 3.8 to the tests

---

ci/aws.yml
ci/azure.yml
ci/google.yml
ci/properties/aws.properties.json
ci/properties/azure.properties.json
ci/properties/google.properties.json

Add some starter workflows that help people build and deploy to cloud providers (AWS, Azure, Google).

Add cloud starter workflows

---

ci/azure.yml
ci/gem-push.yml
ci/google.yml

`@master` should be avoided. See https://github.com/actions/toolkit/blob/master/docs/action-versioning.md.

Don't use actions/checkout@master

---

ci/laravel.yml

Hi there 👋
Add step to configure some [directory permissions](https://github.com/laravel/docs/blob/6.x/installation.md#directory-permissions)
Directories within the `storage` and the `bootstrap/cache` directories should be writable or Laravel will not run.

Add Directory Permissions

---

ci/django.yml
ci/properties/django.properties.json

Possible FIx #212 
Thank you for sending in this pull request. Please make sure you take a look at the [contributing file](https://github.com/actions/starter-workflows/blob/master/CONTRIBUTING.md). Here's a few things for you to consider in this pull request:

Django workflow

---

ci/haskell.yml

Keep ghc version to the latest.

Update ghc to v8.8.2

---

README.md

Tell people how to use these starter workflows.

Update README with guidance

---

ci/azure.yml

[azure/webapps-deploy](https://github.com/marketplace/actions/azure-webapp) action has been enhanced to support deployments to both Azure web apps as well as web app for containers. And we would like to promote the new version of the action as part of the starter templates.
Thanks,
Usha

Updated template to use azure/webapps-deploy@v2

---

ci/dotnet-core.yml

Run a `dotnet restore` step, run tests.
Fixes #208 
Obsoletes #187 and #323 - these were 👍 but we've had some drift in the existing template and needed to resolve conflicts.

Update .NET Core CI template

---

ci/go.yml

Testing in Go is a first-class citizen, any starter workflow should also have a Test step.

Add `Test` step to `go.yml` (Golang starter workflow)

---

ci/docker-publish.yml

Image name was not published as env var but as static "image".

Fix image name as env var

---

ci/properties/wpf-dotnet-core.properties.json

Updated the Wpf dotnetcore workflow icon to dotnetcore

Updated the Wpf dotnetcore workflow icon to dotnetcore

---

ci/properties/tencent.properties.json

Thank you for sending in this pull request. Please make sure you take a look at the [contributing file](https://github.com/actions/starter-workflows/blob/master/CONTRIBUTING.md). Here's a few things for you to consider in this pull request:
Packaging workflows should run on `release` with `types: [ created ]`.
This workflow must only use actions that are produced by the language or ecosystem that the workflow supports.  These actions must be [published to the GitHub Marketplace](https://github.com/marketplace?type=actions).  Workflows using these actions must reference the action using the full 40 …

Set categories to `null` to be in sync with other workflows

---

ci/docker-publish.yml

This resolves an issue created by #472

Fix source image name on docker tag

---

ci/properties/wpf-dotnet-core.properties.json

Update the "Wpf" in the description  to "WPF" to reflect the proper case.

Update the description with the proper case

---

script/sync-ghes/index.ts

See https://github.com/github/c2c-actions-experience/issues/2848

Do not sync workflows without categories to GHES

---

ci/properties/aws.properties.json
ci/properties/azure.properties.json
ci/properties/google.properties.json
ci/properties/ibm.properties.json
ci/properties/tencent.properties.json
ci/properties/terraform.properties.json
script/validate-data/index.ts

This PR adds the creator field to the json properties for partner templates, and appends it do the validation schema

Add creator field and populate for partner templates

---

ci/elixir.yml

EDIT: Like the template for this PR said:
> Use sentence case for the names of workflows and steps, for example "Run tests".
:)

elixir.yml: More consistent case

---

ci/django.yml

Upgrading from `setup-python@v1`

Use actions/setup-python@v2

---

ci/google.yml

It is not:
---
Thank you for sending in this pull request. Please make sure you take a look at the [contributing file](https://github.com/actions/starter-workflows/blob/main/CONTRIBUTING.md). Here's a few things for you to consider in this pull request.
Please **add to this description** at the bottom :point_down:
```
```

Updated google gke workflow(https://github.com/GoogleCloudPlatform/github-actions/blob/master/example-workflows/gke/.github/workflows/gke.yml)

---

code-scanning/README.md

This PR is to add a placeholder README for Code Scanning workflows, to be added in a future PR.

add code scanning placeholder readme

---

ci/blank.yml

Add workflow_dispatch trigger to the default empty workflow

---

CODEOWNERS

Add in codeowners to assist in maintenance

Add in codeowners for this repo

---

ci/properties/openshift.properties.json

Signed-off-by: Tim Etchells <tetchell@redhat.com>
It is not:
---
---
```
```

Add Dockerfile category to openshift workflow

---

automation/properties/manual.properties.json

Add in an icon for the manual workflow, fixes #736. Rebasing off of `main` this time 😄 
---
---
```
```

Add in a person icon

---

ci/cmake.yml

fix context references in cmake template

---

ci/python-publish.yml

In the comment on line `1`, it says "This workflows", but I think that "This workflow" makes more sense.
This is just a simple grammar error and makes no changes to actual code.

Fix grammar error

---

ci/azure.yml

Adding new environment tag

---

ci/google.yml

tested https://github.com/bharathkkb/test-workflow
It is not:
---
---
```
```

feat: Add new GitHub env tag

---

ci/elixir.yml

This line won't break any workflows and is still valid YAML, but it's not necessary.

Remove extra line in Elixir workflow

---

ci/openshift.yml

Modify openshift workflow with
-  v2 version of `push-to-registry` and `buildah-build` actions and
-  add oc-new-app action
-  add step at the top of workflow to check if secrets are set
Signed-off-by: divyansh42 <diagrawa@redhat.com>
---
---
```
```

Modify openshift workflow with v2 version of actions and add oc-new-app

---

code-scanning/README.md

Fix broken link in README.md

---

ci/laravel.yml

---
This PR updates `shivammathur/setup-php` in `laravel` workflow.

Update shivammathur/setup-php in laravel.yml

---

.github/workflows/stale.yml

`repo-token` defaults to `github.token`
https://github.com/actions/stale/blob/043fbbdea3e060a5aa2949408ad8e4b52988f420/action.yml#L5-L8

chore: update `stale.yml`

---

ci/dotnet-desktop.yml
ci/msbuild.yml

---
update setup-msbuild and fix add path bug:  #893

update setup-msbuild version and fix add path bug.

---

code-scanning/tfsec.yml

Update the tfsec ref point

---

ci/deno.yml

Also adds formatting and linting to the workflow (like dart workflow), and use uniform capitalization.
We released the denoland/setup-deno extension a few weeks ago in the https://github.com/denoland org as the official setup action.

switch to official denoland/setup-deno action

---

ci/docker-publish.yml

Follow-up #914 
Reduce and simplify to one job that can be used on any events.
cc @clarkbw @pfleidi

Simplify Docker publish workflow

---

ci/openshift.yml

---
---
```
```
Fixes https://github.com/redhat-actions/starter-workflows/issues/3

Replace oc-installer with tools-installer

---

ci/go.yml

go: update to use 1.16

---

ci/blank.yml

---
---
```
```
This is a workflow.  An action is what may be run in an individual step of the workflow.

action -> workflow in blank.yml

---

ci/properties/blank.properties.json

As a step to make telemetry to see template creator popularity. I am adding this field to the blank template. 
---
---
```
```

Updated blank.properties.json to have creator field

---

ci/pylint.yml

pylint: use python 3.9 and setup-python@v2

---

ci/node.js.yml

Add cache usage to the node.js starter-workflow

---

ci/go.yml
ci/grunt.yml
ci/gulp.yml
ci/properties/grunt.properties.json
ci/properties/gulp.properties.json
ci/properties/webpack.properties.json
ci/webpack.yml

Added templates for gulp + grunt + webpack

---

ci/go.yml
code-scanning/flawfinder.yml
code-scanning/properties/flawfinder.properties.json
icons/flawfinder.svg

---
---
```
```
cc @eddynaka @david-a-wheeler

Add Flawfinder Code Scanning Workflow

---

ci/properties/makefile.properties.json

Update `categories` from `makefile.properties.json` to include `"Continuous integration"`
To be inline with - https://github.com/actions/starter-workflows/pull/1094

add `Continuous integration` to makefile props

---

deployments/properties/aws.properties.json
deployments/properties/azure.properties.json

Added Node to Azure, AWS Templates for bug_bash

---

README.md

This PR fixes the `Directory structure` section on README to include the `deployments` folder description.

Directory structure updated

---

deployments/properties/alibabacloud.properties.json
deployments/properties/google.properties.json
deployments/properties/ibm.properties.json
deployments/properties/tencent.properties.json
deployments/properties/terraform.properties.json

This is to address the bug: https://github.com/github/github/issues/194792. When we enable CD ordering, for the current CD templates that are based on Dockerfile to show up, we need these changes. FYI, for [Openshift](https://github.com/actions/starter-workflows/blob/7f30309ccedb0e3dee186e0ee58c232752a78e24/deployments/properties/openshift.properties.json#L6), we already have it in place.
---
---
```
```

Added dockerfile to relevant CD template categories.

---

code-scanning/mayhem-for-api.yml

A free plan is now in place with a professional trial that may be opted into afterward.
---
---
```
```

Remove mention of trial for Mayhem for API

---

ci/elixir.yml

---
```
```
---
- setup action got renamed into `setup-beam`
- update elixir and erlang versions
cc @andymckay @joshmgross

elixir: refresh dependencies

---

deployments/google.yml
deployments/properties/google.properties.json

Update google deployment starter workflow (partner_templates)

---

deployments/azure-webapps-php.yml
deployments/azure-webapps-python.yml

Use setup-python action cache option instead of cache action for Python Azure web App template
Adding commit SHA for 3rd party actions
---
---
```
```

Updating azure partner templates to use commitId for 3rd party actions and setup actions cache.

---

code-scanning/pmd.yml

This updates the existing code scanning workflow "pmd":
- Use pmd/pmd-github-action@6d98898be0d59f46ec37dafcea33d8f8f55acfd1 which is v1.1.0
- Use temurin as java distribution
---
---
```
```

Update pmd to v1.1.0

---

code-scanning/checkmarx.yml

Update checkmarx.yml attributes : "uses","project","teams","scanners","params".

---

code-scanning/scorecards.yml

Scorecards: Updates for release

---

deployments/azure-container-webapp.yml

---
This PR fixes an indentation error in the second job of the container workflow for Azure Webapps.

Fix indentation error

---

ci/node.js.yml

The word 'install' is not a noun.
very sorry if I have made this pr twice, this is my first time contributing to a project

fixed grammatical error in node.js.yml

---

code-scanning/scorecards.yml

We fixed a small issue and need to update the hash
---
---
```
```

Scorecards: update hash for v1.0.2

---

deployments/google.yml

update google workflow

---

code-scanning/properties/apisec-scan.properties.json
code-scanning/properties/cloudrail.properties.json
code-scanning/properties/pmd.properties.json
code-scanning/properties/scorecards.properties.json

Some code scanning workflows such as ApiSec, pmd, cloudRail, mobsf has either large description or name or creator which causes bad user experience for starter workflows.  This PR fixes these code scanning workflows.
---
---
```
```

Fixing some code scanning workflows description

---

ci/gradle-publish.yml
ci/gradle.yml

This PR updates the SHA for `gradle/gradle-build-action` to point to the `v2.1.3` release.
No other workflow changes are included
---
---
```
```

Update for gradle/gradle-build-action@v2.1.3

---

code-scanning/njsscan.yml

This PR adds token permissions for code-scanning/njsscan.yml. The permissions were added using https://app.stepsecurity.io/.
---
---
```
```

Add token permissions for code-scanning/njsscan.yml

---

code-scanning/stackhawk.yml

This PR adds token permissions for code-scanning/stackhawk.yml. The permissions were added using https://app.stepsecurity.io/.
---
---
```
```

Add token permissions for code-scanning/stackhawk.yml

---

code-scanning/semgrep.yml

This PR adds `github_token` permissions in `code-scanning/semgrep.yml`. The `token` permissions were added using https://app.stepsecurity.io/
---
---
```
```

Added github_token permissions in code-scanning/semgrep.yml

---

code-scanning/codacy.yml

This PR adds token permissions to code-scanning/codacy.yml. The permissions were added using https://app.stepsecurity.io/.
---
---
```
```

Add token permissions for code-scanning/codacy.yml

---

ci/msbuild.yml

Added PR trigger
---
---
```
```

Added PR trigger

---

code-scanning/scorecards.yml

Update hash for scorecard's v1.0.4 release

---

code-scanning/mobsf.yml

This PR adds token permissions for code-scanning/mobsf.yml. The permissions were added using https://app.stepsecurity.io/.
---
---
```
```

Add token permissions for code-scanning/mobsf.yml

---

code-scanning/prisma.yml

This PR adds token permissions to code-scanning/prisma.yml. The permissions were added using https://app.stepsecurity.io/.
---
---
```
```

Add token permissions for code-scanning/prisma.yml

---

code-scanning/sysdig-scan.yml

This PR adds token permissions to code-scanning/sysdig-scan.yml. The permissions were added using https://app.stepsecurity.io/.
---
---
```
```

Add token permissions for code-scanning/sysdig-scan.yml

---

code-scanning/veracode.yml

This PR adds token permissions to code-scanning/veracode.yml. The permissions were added using https://app.stepsecurity.io/.
---
---
```
```

Add token permissions for code-scanning/veracode.yml

---

code-scanning/apisec-scan.yml

This PR adds token permissions for code-scanning/apisec-scan.yml. The permissions were added using https://app.stepsecurity.io/.
---
---
```
```

Add token permissions for code-scanning/apisec-scan.yml

---

code-scanning/brakeman.yml

This PR adds token permissions for code-scanning/brakeman.yml. The permissions were added using https://app.stepsecurity.io/.
---
---
```
```

Add token permissions for code-scanning/brakeman.yml

---

code-scanning/msvc.yml

This PR adds token permissions to code-scanning/msvc.yml. The permissions were added using https://app.stepsecurity.io/.
---
---
```
```

Add token permissions for code-scanning/msvc.yml

---

deployments/azure-kubernetes-service-helm.yml
deployments/azure-kubernetes-service-kompose.yml
deployments/azure-kubernetes-service-kustomize.yml
deployments/properties/azure-kubernetes-service-helm.properties.json
deployments/properties/azure-kubernetes-service-kompose.properties.json
deployments/properties/azure-kubernetes-service-kustomize.properties.json
deployments/properties/azure-kubernetes-service.properties.json

Port AKS templates changes from `partner_templates` branch. Original PR: https://github.com/actions/starter-workflows/pull/1403
---
---
```
```

Port reworked AKS templates to main

---

ci/elixir.yml
ci/haskell.yml
ci/php.yml
ci/symfony.yml
code-scanning/codescan.yml
deployments/azure-webapps-dotnet-core.yml
deployments/azure-webapps-php.yml

Update cache action to v3

---

deployments/azure-kubernetes-service-helm.yml
deployments/azure-kubernetes-service-kompose.yml
deployments/azure-kubernetes-service-kustomize.yml
deployments/azure-kubernetes-service.yml

Update AKS workflows to not use imagePullSecrets

---

ci/elixir.yml

This PR adds `github_token` permission in `ci/elixir.yml`, The permissions were added using https://app.stepsecurity.io.
---
---
```
```

Add github_token permission in ci/elixir.yml

---

deployments/azure-kubernetes-service-helm.yml
deployments/azure-kubernetes-service-kompose.yml
deployments/azure-kubernetes-service-kustomize.yml
deployments/azure-kubernetes-service.yml

Removed actions read permission from createSecret and buildImage steps

---

code-scanning/properties/dependency-review.properties.json

Addresses https://github.com/actions/starter-workflows/issues/1549

Fix typo "depdendencies" => "dependencies"

---

deployments/azure-kubernetes-service-helm.yml
deployments/azure-kubernetes-service-kustomize.yml

Added checkout step to aks helm starter workflow

---

code-scanning/scorecards.yml

✨ Scorecard v1.1.0 hash bump

---

code-scanning/scorecards.yml

✨ Bump scorecard hash for v1.1.1

---

code-scanning/properties/soos-dast-scan.properties.json
code-scanning/soos-dast-scan.yml
icons/soos.svg

Add SOOS DAST starter workflow

---

code-scanning/anchore.yml

Whenever a security issue is found the `scan action` fails the build and the step, which causes the workflow to fail before uploading the results to Code Scanning.
This change turns the error into a warning.
---
---
```
```

Set `fail-build` property to false

---

code-scanning/soos-dast-scan.yml

Changes pending from this initial work https://github.com/actions/starter-workflows/pull/1582#discussion_r883024611
---
---
```
```

Update SOOS DAST action to use code-ql upload sarif and change tag

---

ci/gradle-publish.yml
ci/gradle.yml

This PR updates the SHA for `gradle/gradle-build-action` to point to the `v2.2.1` release.
No other workflow changes are included.
https://github.com/gradle/gradle-build-action/releases/tag/v2.2.1
---
---
```
```

Update to v2.2.1 of gradle-build-action

---

ci/go-ossf-slsa3-publish.yml

Update OSSF SLSA builder to v1.1.1

---

code-scanning/trivy.yml

This version of trivy-action fixed an issue reported by GitHub. The detail is in https://github.com/aquasecurity/trivy/issues/2357.

Update trivy-action to fix the performance issue

---

code-scanning/dependency-review.yml

This PR bumps the version of the Dependency Review action that we suggest to customers.

Update the sample version of the Dependency Review action.

---

ci/go-ossf-slsa3-publish.yml

---
---
```
```
/cc @ianlewis @asraa

Bump version for SLSA Go builder

---

pages/properties/gatsby.properties.json
pages/properties/hugo.properties.json
pages/properties/jekyll-gh-pages.properties.json
pages/properties/jekyll.properties.json
pages/properties/nextjs.properties.json
pages/properties/nuxtjs.properties.json
pages/properties/static.properties.json

This PR addresses the feedback from https://github.com/actions/starter-workflows/pull/1645 and:
- Drops `creator` for the Pages starter workflows
- Add language/platform to categories
---
---
```
```

Address feedback from PR #1645

---

pages/static.yml

This updates #1645
All other files refers v1.
* https://github.com/actions/starter-workflows/blob/1c7042ea97a8e1a5d5d3bc0d75ab33984912f3d4/pages/nuxtjs.yml#L90
* https://github.com/actions/starter-workflows/blob/1c7042ea97a8e1a5d5d3bc0d75ab33984912f3d4/pages/nextjs.yml#L95
* https://github.com/actions/starter-workflows/blob/1c7042ea97a8e1a5d5d3bc0d75ab33984912f3d4/pages/jekyll.yml#L53
* https://github.com/actions/starter-workflows/blob/1c7042ea97a8e1a5d5d3bc0d75ab33984912f3d4/pages/jekyll-gh-pages.yml#L50
* https://github.com/actions/starter-workflows/blob/1c7042ea97a8e1a5d5d3bc0d75ab33984912f3d4/pages/hugo.yml#L66
* https://github.com/actions/starter-workflows/blob/1c7042ea97a8e1a5d5d3bc0d75ab33984912f3d4/pages/gatsby.yml#L96
Tags https://github.com/actions/deploy-pages/tags
---
---
--- …

Refer `actions/deploy-pages` stable tag in `pages/static`

---

code-scanning/anchore-syft.yml
code-scanning/properties/anchore-syft.properties.json

This PR adds a starter workflow using the [Anchore scan-action](https://github.com/anchore/sbom-action), which provides dependency scanning of containers and directories using the [Anchore Syft tool](https://github.com/anchore/syft). This workflow also uploads to the results to the GitHub Dependency submission API.
---
---
```
```

Add Anchore Syft SBOM scan workflow

---

CODEOWNERS

Update CODEOWNERS to have pages team

---

pages/hugo.yml

Fixes #1683
Addresses:
- #1683
- I am currently an active GitHub employee :octocat: 
---
---
```
```

Pages: Explicitly set Hugo environment as production

---

pages/hugo.yml

Fixes https://github.com/actions/starter-workflows/issues/1683
Addresses my earlier confusion as explained in:
- https://github.com/actions/starter-workflows/issues/1683#issuecomment-1223058088
Reverts:
- https://github.com/actions/starter-workflows/pull/1689
- I am currently an active GitHub employee :octocat: 
---
---
```
```

Pages: Explicitly set Hugo environment variables as production

---

pages/jekyll.yml

Jekyll docs about a Jekyll environment see: [jekyllrb.com/docs/configuration/environments](https://jekyllrb.com/docs/configuration/environments/).
---
---
```
```

Pages: Set Jekyll environment as production

---

pages/jekyll.yml

The Pages starter workflow for building Jekyll sites is using the `ruby/setup-ruby` community Action without following the PR guidelines of this repository:
> - [ ] This workflow must _only_ use actions that are produced by the language or ecosystem that the workflow supports.  These actions must be [published to the GitHub Marketplace](https://github.com/marketplace?type=actions).  We require that these actions be referenced using the full 40 character hash of the action's commit instead of a tag.  Additionally, workflows must include the following comment at the top of the workflow file:
>    ```
>    # This workflow uses actions that are not certified by GitHub.
>    # They are provided by a third-party and are governed by
>    # separate terms of service, privacy policy, and support
> …
```

Pages: Bring use of `ruby/setup-ruby` into compliance

---

pages/gatsby.yml
pages/hugo.yml
pages/jekyll-gh-pages.yml
pages/jekyll.yml
pages/nextjs.yml
pages/nuxtjs.yml
pages/static.yml

Cherry picks commits from https://github.com/actions/starter-workflows/pull/1688 into the `ghes` branch.

Apply pages workflow updates to ghes

---

ci/ruby.yml
ci/rubyonrails.yml
code-scanning/brakeman.yml
code-scanning/puppet-lint.yml
code-scanning/rubocop.yml
pages/jekyll.yml

Update all usages of `ruby/setup-ruby` to the pinned SHA of its [latest release `v1.115.3`](https://github.com/ruby/setup-ruby/releases/tag/v1.115.3)
Closes #1642
---
---
```
```

Update all usages of `ruby/setup-ruby` to latest

---

pages/hugo.yml

REF: https://github.com/gohugoio/hugo/releases

use latest version of Hugo

---

code-scanning/frogbot-scan-and-fix.yml
code-scanning/frogbot-scan-pr.yml

Update JFrog Frogbot permissions and Tag

---

.github/workflows/sync-ghes.yaml
code-scanning/frogbot-scan-and-fix.yml
deployments/alibabacloud.yml
deployments/aws.yml
deployments/azure-container-webapp.yml
deployments/azure-kubernetes-service-helm.yml
deployments/azure-kubernetes-service-kompose.yml
deployments/azure-kubernetes-service-kustomize.yml
deployments/azure-kubernetes-service.yml
deployments/azure-staticwebapp.yml
deployments/azure-webapps-dotnet-core.yml
deployments/azure-webapps-java-jar.yml
deployments/azure-webapps-node.yml
deployments/azure-webapps-php.yml
deployments/azure-webapps-python.yml
deployments/google-cloudrun-docker.yml
deployments/google-cloudrun-source.yml
deployments/google.yml
deployments/ibm.yml
deployments/tencent.yml
deployments/terraform.yml

This regex `^(?!.*(default-branch)).*branches:.*` should help find anything not using [$default-branch](https://github.blog/changelog/2020-07-22-github-actions-better-support-for-alternative-default-branch-names/).

branches: [ `$default-branch` ]

---

code-scanning/scorecards.yml

- Upgraded scorecard action to v2.0.0 
https://github.com/ossf/scorecard-action/commit/13ec8c77e8a5dae7e0a0d47bde3e3004df15d34f
Signed-off-by: naveensrinivasan <172697+naveensrinivasan@users.noreply.github.com>
---
---
```
```

Upgraded scorecard action to v2.0.0

---

ci/node.js.yml
ci/npm-grunt.yml
ci/npm-gulp.yml
ci/webpack.yml

---
---
```
```
This is a successor to #1533 as that PR seems to have gone stale / inactive.
It removes Node12 and adds Node18 instead for alle Node.js related CI Workflows.

Adds Node 18 and removes Node 12

---

code-scanning/powershell.yml

---
---
- [ x] Should be contained in a `.yml` file with the language or platform as its filename, in lower, [_kebab-cased_](https://en.wikipedia.org/wiki/Kebab_case) format (for example, [`docker-image.yml`](https://github.com/actions/starter-workflows/blob/main/ci/docker-image.yml)).  Special characters should be removed or replaced with words as appropriate (for example, "dotnet" instead of ".NET").
- [ x] Should use sentence case for the names of workflows and steps (for example, "Run tests").
- [ x] Should be named _only_ by the name of the language or platform (for example, "Go", not "Go CI" or "Go Build").
- [ x] Should include comments in the workflow for any parts that are not obvious or could use clarification.
- [ x] Should specify least …

Updated powershell to v1.1 commit

---

.github/workflows/sync-ghes.yaml

Adding manual trigger to sync ghes script incase it doesn't run, automatically

Adding manual trigger to sync ghes script

---

script/sync-ghes/settings.json

Add actions/cache to list of enabledActions on GHES

Add actions/cache to list of enabledActions

---

code-scanning/scorecards.yml

Includes bug fixes
---
---
```
```

Update to scorecard-action:v2.0.3

---

ci/docker-publish.yml

Enable caching by default for docker builds.

---

code-scanning/frogbot-scan-and-fix.yml
code-scanning/frogbot-scan-pr.yml
starter-workflows.iml

Update JFrog Frogbot's version

---

ci/docker-publish.yml

Signed-off-by: Batuhan Apaydın <batuhan.apaydin@trendyol.com>
---
---
```
```

chore: upgrade cosign-installer version to latest

---

code-scanning/anchore.yml
code-scanning/properties/anchore-syft.properties.json
code-scanning/properties/anchore.properties.json

Update Anchore Grype scan action

---

code-scanning/nowsecure-mobile-sbom.yml
code-scanning/properties/nowsecure-mobile-sbom.properties.json

Add NowSecure Mobile SBOM starter workflow

---

ci/dotnet-desktop.yml
ci/dotnet.yml

The version of the `setup-dotnet` was recently updated to `v3`. The dotnet starter workflows should reflect this change to allow more customers to use the new action version.
Closes [this issue](https://github.com/actions/runner-images-internal/issues/4329)
---
---

Update starter-workflows to use setup-dotnet@v3

---

code-scanning/properties/ethicalcheck.properties.json

Updated the description

---

ci/maven.yml

This change adds a new step to the default workflow which adds transitive dependency information to the dependency graph. This action was built by a GitHubber, @peter-murray, and is currently published to the `advanced-security` organization. I think we could move this action to the actions org if that's a hard requirement for this one. 
---
---
```
```

Add dependency graph to Maven workflows

---

code-scanning/zscaler-iac-scan.yml

update zscaler iac scan version

---

code-scanning/codeql.yml

We now officially support Go in code scanning as a language that may be either autobuilt, or manually built (see [changelog](https://github.blog/changelog/2022-10-25-codeql-code-scanning-now-supports-customizing-build-configurations-for-go-analysis/) post). 
To correspond with this change, we should add it to the list of compiled languages in the starter code scanning workflow.
---
---
- [N/A] Should be preserved under [the `ci` directory](https://github.com/actions/starter-workflows/tree/main/ci).
- [N/A] Should include a matching `ci/properties/*.properties.json` file (for example, [`ci/properties/docker-publish.properties.json`](https://github.com/actions/starter-workflows/blob/main/ci/properties/docker-publish …

Add Go to code scanning autobuild comment

---

deployments/azure-kubernetes-service-helm.yml
deployments/azure-kubernetes-service-kompose.yml
deployments/azure-kubernetes-service-kustomize.yml
deployments/azure-kubernetes-service.yml

---
---
```
```
This PR bumps the AKS workflows to use the latest version of our actions. Additionally, it removes the image pull secret style ACR interaction in favor of attach-acr (a security best practice).

Bump aks workflows to latest versions

---

code-scanning/scorecards.yml

scorecard: update the token doc

---

pages/gatsby.yml

Closes https://github.com/actions/starter-workflows/pull/1828
Just rebasing since we don't have edit permissions on that one. 🤷🏻‍♂️ 
As noted by @torn4dom4n:
> Gatsby 5 uses Node 18, [see](https://www.gatsbyjs.com/blog/gatsby-5-upgrade-say-no-to-yolo/) so I think this repo should use Node 18 by default.
---
---
```
```

Using Node.js 18.x for Gatsby

---

README.md

Readme updated with instructions to testing templates before publishing

Add instructions to test templates

---

ci/go.yml

Go 1.18 will be at end of life sometime within the coming months (Q1 2023). Go 1.19 will be around until Q3 2023, by which point 1.20 will have been released.
- ~[ ] Prior to submitting a new workflow, please apply to join the GitHub Technology Partner Program: [partner.github.com/apply](https://partner.github.com/apply?partnershipType=Technology+Partner).~ N/A: this is an existing workflow.
---
---
```
```

Update Go version to 1.19

---

code-scanning/codeql.yml

Added comments explaining which values should be used if the user would like to scan Kotlin or TypeScript.
---
---
```
```

Add explanation on which value to use to scan Kotlin and TypeScript

---

pages/hugo.yml

Fix and improve Hugo starter action

---

ci/python-package-conda.yml

Add quotes to python version in python conda

Fix python version problem

---

ci/generator-generic-ossf-slsa3-publish.yml
ci/go-ossf-slsa3-publish.yml

Since GitHub's deprecation of `set-ouput`, the SLSA reusable workflows needed to change. This PR updates them to the latest version.
Fixes https://github.com/slsa-framework/slsa-github-generator/issues/1302
Signed-off-by: Mihai Maruseac <mihaimaruseac@google.com>
---
---
```
```

Update SLSA generators to v1.4.0

---

code-scanning/bandit.yml

Try to fix lint error

---

code-scanning/bandit.yml
deployments/azure-kubernetes-service-helm.yml
deployments/azure-kubernetes-service-kompose.yml
deployments/azure-kubernetes-service-kustomize.yml
deployments/azure-kubernetes-service.yml

---
---
```
```
Adding Kubelogin action after users experienced issues connecting to cluster.

Update AKS Starter Workflows to Use Kubelogin

---

code-scanning/codeql.yml

Correct indentation of "run" example

---

pages/astro.yml
pages/gatsby.yml
pages/hugo.yml
pages/jekyll-gh-pages.yml
pages/jekyll.yml
pages/nextjs.yml
pages/nuxtjs.yml
pages/static.yml

In response to `actions/configure-pages@v3.0.0` being released today for this PR:
- https://github.com/actions/configure-pages/pull/48
---
---
```
```

Update all Pages starter workflows to use `actions/configure-pages@v3`

---

.github/workflows/lint.yaml

This was triggering linting on target branch without merge changes which lead to separate updation of template when lint start failing after merge

Change pull request target to pull request trigger

---

automation/label.yml

Change event to pull_request_target

---

code-scanning/defender-for-devops.yml
code-scanning/properties/defender-for-devops.properties.json

Add defender for devops workflow

---

code-scanning/defender-for-devops.yml
code-scanning/properties/defender-for-devops.properties.json

fixed typo

---

ci/elixir.yml
ci/msbuild.yml
ci/symfony.yml

Adds third party action usage comment

Update comment for third party action usage

---

pages/properties/mdbook.properties.json

Follow up to #1677.
I noticed the capitalization is styled as `mdBook`, so this ensures it shows up in our UI that way.
cc @Decodetalkers as the original contributor
---
---
```
```

Use proper styling for `mdBook`

---

pages/mdbook.yml

We missed a few more instances of the proper casing for `mdBook`. 😅 
Follow-up to:
- https://github.com/actions/starter-workflows/pull/1975
- https://github.com/actions/starter-workflows/pull/1677
---
---
```
```

Update casing of mdBook within copy in mdbook.yml

---

pages/astro.yml
pages/gatsby.yml
pages/nextjs.yml
pages/nuxtjs.yml

Spotted this little typo today. 🙂 
Co-authored-by: Rizèl Scarlet <blackgirlbytes@github.com>

chore: fix package(r) manager typo

---

code-scanning/codeql.yml

CodeQL Swift analysis is best supported on macOS.
In preparation for CodeQL supporting Swift analysis in beta, adjust the CodeQL starter workflow template to run the `swift` matrix job on `macos-latest`, and all other matrix jobs on `ubuntu-latest`. This does not affect the matrix itself.
---
---
```
```

CodeQL: Run on macOS by default if the target language is Swift

---

deployments/azure-functions-app-container.yml
deployments/azure-functions-app-dotnet.yml
deployments/azure-functions-app-java-gradle.yml
deployments/azure-functions-app-java.yml
deployments/azure-functions-app-nodejs.yml
deployments/azure-functions-app-powershell.yml
deployments/azure-functions-app-python.yml

This PR fixes: https://github.com/actions/starter-workflows/issues/2028
| Error when running `azure-functions-app-python.yml` in its current state|
| -- |
|  ![CleanShot 2023-04-24 at 10 03 35](https://user-images.githubusercontent.com/1554630/234066436-e0a036f9-2cf0-4bd2-976c-beeba8a6ddb9.png) |
| Actions Syntax highlighting showing error |
| -- |
| ![image](https://user-images.githubusercontent.com/1554630/234066670-ba3f18b8-556c-47bf-9c4e-37db54f0c2dc.png) |
---
---
```
```

Corrects the syntax for `on: push: branches:` so that the array is inline

---

code-scanning/codeql.yml

Some projects observed intermittent build timeouts with Swift. In case this happens, and our CodeQL-level mitigations do not prevent the problem, we want to avoid using up 6h of the customer's billed macOS Actions minutes (which is the default timeout), so we suggest a reduced timeout of 2h.
This value is chosen to accommodate the total job time (build + CodeQL extraction + CodeQL analysis) we expect for large Swift projects. We may choose to adjust it in future.
- [N/A] Prior to submitting a new workflow, please apply to join the GitHub Technology Partner Program: [partner.github.com/apply](https://partner.github.com/apply?partnershipType=Technology+Partner).
---
---
**For _Code Scanning_ workflows, the …

CodeQL: Reduce job timeout to 2h if the target language is Swift

---

code-scanning/properties/codeql.properties.json

- Swift support for CodeQL will soon be in public beta.
---
---
```
```

Add Swift to the list of CodeQL-supported languages

---

pages/astro.yml
pages/gatsby.yml
pages/hugo.yml
pages/jekyll-gh-pages.yml
pages/jekyll.yml
pages/mdbook.yml
pages/nextjs.yml
pages/nuxtjs.yml
pages/static.yml

The GitHub Pages team recently released [`actions/upload-pages-artifact@v2.0.0`](https://github.com/actions/upload-pages-artifact/releases/tag/v2.0.0), which speeds up Pages deployment preparation (artifact uploading) by removing the previously built-in `chmod` commands to fix potentially invalid file permissions.
I have verified these changes against our Pages starter workflow regression testing repos. 🧪 ✅ 👍🏻 
---
---
```
```

Update all Pages starter workflows to use upload-pages-artifact@v2

---

ci/gem-push.yml

👋🏻 Friendly update to move the gem workflow from `actions/setup-ruby` to `ruby/setup-ruby`, putting it in line with the [ruby.yml](https://github.com/actions/starter-workflows/blob/main/ci/ruby.yml#L33).  I'd tried this out and got a notice that `actions/setup-ruby` was deprecated and to use this instead.  Seems like this workflow was a bit of an oversight, as the other ruby starters in this repo have already been moved.
---
---
```
```

move gem workflow to ruby/setup-ruby, same as ruby

---

ci/go.yml

In scope of this pull request we update setup-go major tag from v3 -> v4 (we enabled cache by default). Besides, we update go version to the latest and use single quotes because YAML parser's behavior, which interprets non-wrapped values as numbers and, in the case of version `1.20`, trims it down to `1.2`.
---
---
```
```

Update setup-go and latest go versions

---

ci/docker-publish.yml
deployments/azure-container-webapp.yml

follow-up https://github.com/docker/metadata-action/issues/314#issuecomment-1655785744
Docker actions are outdated, let's update to latest stable to avoid drifting.
___
---
---
```
```

update docker actions to latest stable

---

code-scanning/crunch42.yml
code-scanning/properties/crunch42.properties.json

Update to latest audit code version

---

code-scanning/codeql.yml

This PR updates the version of actions used in the starter workflow for CodeQL.
Both the CodeQL Actions and `actions/checkout` are updated to reference the latest version, running on `node20`.
---
---
```
```

update codeql.yml to reference node20 actions

---

ci/gradle-publish.yml
ci/gradle.yml

This PR updates the existing `gradle.yml` and `gradle-publish.yml` starter workflows for recent updates to `gradle/gradle-build-action`.
- Replace uses of `gradle/gradle-build-action` with `gradle/actions/setup-gradle`
- Split "Setup Gradle" step out of "Run Gradle" steps
- Add separate Job using `gradle/actions/dependency-submission` (flagged as optional)
- Bump version hashes to use `v3.0.0` of Gradle actions
- Bump to Node20-compatible versions of `actions/checkout` and `actions/setup-java`
- Bump to setup JDK 17
---
---
```
```

Update for `gradle/actions@v3.0.0` release

---

code-scanning/tfsec.yml

This pull request includes a minor update to the `code-scanning/tfsec.yml` file. The change updates the version of `tfsec-sarif-action` used in the `Run tfsec` job from `9a83b5c3524f825c020e356335855741fd02745f` to the latest `21ded20e8ca120cd9d3d6ab04ef746477542a608`. This is incorporates recent improvements or fixes from the newer version of `tfsec-sarif-action`.
Also note: 
```
======================================================
tfsec is joining the Trivy family
tfsec will continue to remain available 
for the time being, although our engineering 
attention will be directed at Trivy going forward.
You can read more here: 
https://github.com/aquasecurity/tfsec/discussions/[19](https://github.com/octodemo/felickz-terragoat/actions/runs/8097652285/job/22129180892#step:4:20)94 …
```

tfsec latest v0.1.4

---

code-scanning/detekt.yml
code-scanning/endorlabs.yml
code-scanning/rust-clippy.yml
deployments/alibabacloud.yml
pages/hugo.yml

Bump workflow actions of various starter files

---

pages/astro.yml

Fix: astro.yml for yarn based project

---

pages/astro.yml
pages/gatsby.yml
pages/hugo.yml
pages/jekyll-gh-pages.yml
pages/jekyll.yml
pages/mdbook.yml
pages/nextjs.yml
pages/nuxtjs.yml
pages/static.yml

Most notably, the use of [`actions/configure-pages@v5`](https://github.com/actions/configure-pages/releases/tag/v5.0.0) advances our support for the Next.js static site generator from `<14.0.0` to `>=v13.3.0` (see [Next.js version history](https://nextjs.org/docs/pages/building-your-application/deploying/static-exports#version-history) for a pretty clear explanation).
---
---
```
```

Update all Pages workflows to use `actions/configure-pages@v5`

---

pages/astro.yml
pages/gatsby.yml
pages/hugo.yml
pages/jekyll-gh-pages.yml
pages/mdbook.yml
pages/nextjs.yml
pages/nuxtjs.yml
pages/static.yml

Revert Pages starter workflows to latest versions supported for GHES (in the `ghes` branch).
---
---
```
```

Revert Pages actions to last ones compatible with GHES

---

code-scanning/policy-validator-cfn.yaml
code-scanning/policy-validator-tf.yaml
code-scanning/properties/policy-validator-cfn.properties.json
code-scanning/properties/policy-validator-tf.properties.json

Adding a sample starter workflow to demonstrate how customers can use the `aws-actions/cloudformation-aws-iam-policy-validator` & `aws-actions/terraform-aws-iam-policy-validator` as a re-usable workflow 
---
---
```
```

Add starter-workflows for Policy Validator

---

script/sync-ghes/settings.json

Removes Pages from the automation to update our workflows for now until we support artifacts v4 in `GHES` 
---
---
```
```

Remove Pages starter workflows from the sync automation

---

pages/astro.yml
pages/gatsby.yml
pages/hugo.yml
pages/jekyll-gh-pages.yml
pages/mdbook.yml
pages/nextjs.yml
pages/nuxtjs.yml
pages/static.yml

Second attempt at https://github.com/actions/starter-workflows/pull/2366 now that the [syncing automation has been tamed](https://github.com/actions/starter-workflows/pull/2376).
---
---
```
```

Ghes pages

---

pages/astro.yml
pages/gatsby.yml
pages/hugo.yml
pages/jekyll-gh-pages.yml
pages/mdbook.yml
pages/nextjs.yml
pages/nuxtjs.yml
pages/static.yml

GHES 3.13 is not including configure-pages@v5 so downgrading to v4.
---
---
```
```

Ghes pagesv4

---

ci/gradle.yml

Fix typo in grade starter workflow

---

code-scanning/sonarcloud.yml

This Pull Request follows the release of a new version (v2.2.0) for the SonarCloud action.

Update sonarcloud.yml after latest release of the action

---

code-scanning/policy-validator-cfn.yaml
code-scanning/policy-validator-tf.yaml

---
---
- [ This workflow must _only_ use actions that are produced by GitHub, [in the `actions` organization](https://github.com/actions), **or**
```
```
Our GitHub Actions (https://github.com/aws-actions/cloudformation-aws-iam-policy-validator, https://github.com/aws-actions/terraform-aws-iam-policy-validator) have been updated to support new AWS Access Analyzer functionality. 
- This PR updates our starter workflow to be in sync with the latest version of our GitHub Actions. 
- This PR also includes a minor fix to the name of the `reference-policy` argument in `policy-validator-cfn.yaml`

Update policy validator starter workflows

---

ci/dotnet-desktop.yml
code-scanning/msvc.yml
code-scanning/scorecard.yml
code-scanning/xanitizer.yml
deployments/azure-webapps-dotnet-core.yml
deployments/azure-webapps-java-jar-gradle.yml
deployments/azure-webapps-java-jar.yml
deployments/azure-webapps-node.yml
deployments/azure-webapps-php.yml
deployments/azure-webapps-python.yml

Reverts actions/starter-workflows#2383

Revert "Artifacts: Update all workflows to use Artifacts V4"

---

code-scanning/frogbot-scan-and-fix.yml
code-scanning/frogbot-scan-pr.yml

---
---
```
```
---
This pull request includes the following changes:
- Updates Frogbot to version 2.21.2
- Fixes broken documentation links
- Updates Checkout Action to version 4

Frogbot: Update to 2.21.2

---

.github/labeler.yml

Update the labeler config to work with v5
Follow up to https://github.com/actions/starter-workflows/pull/2384

Update labeler.yml for v5

---

code-scanning/soos-dast-scan.yml

Update soos-dast-scan.yml hash

Update soos-dast-scan.yml hash

---

code-scanning/codeql.yml

Spurious intermittent timeouts are no longer expected on Swift.
---
---
```
```

CodeQL: Remove Swift 2h timeout

---

deployments/google-cloudrun-docker.yml
deployments/google-cloudrun-source.yml
deployments/google.yml

google: update workflow versions and instructions

---

code-scanning/codeql.yml

Avoid this scenario:
- Same name when switching Code Scanning to/from default setup to advanced setup
- There is no indicator in the workflow that it is a dynamic yaml vs manual yaml (unless you click into it and see a `.yml` file listed)
- We dont "disable" the default workflow when switching back to advanced - no visual disable indicator that direction either
---
---
```
```

CodeQL - Add unique workflow name `CodeQL Advanced` vs default setup's `CodeQL`

---

code-scanning/soos-dast-scan.yml

SOOS Dast Feature Update

---

automation/properties/summary.properties.json
automation/summary.yml

Add summary preview workflow
