actions/starter-workflows

- ci/go.yml
Fixes a small bug in the template, `use` should be `uses`
> Go template - use->uses

- ci/node.js.yml
Node packages should be tested in all current versions by default.  We are working on setting some guidelines as mentioned in https://github.com/actions/setup-node/issues/25, so until aliases are supported we would want to keep this list up to date with the node LTS plan: https://nodejs.org/en/about/releases/
As I am not in the beta, I do not have the ability to try these out, but I wanted to make sure we setup people up with the best practice from day one, so figured I would get this in early.  I copied from the python example, so think it should work but am happy to make any changes necessary to get this merged.
> Test node in all current versions

- ci/jekyll.yml
This will error out because `Gemfile.lock` doesn't have the right permissions in the `/srv/jekyll` dir.
```
There was an error while trying to write to `/srv/jekyll/Gemfile.lock`. It is
likely that you need to grant write permissions for that path.
```
To reproduce, run this workflow on a jekyll site repo.
After some experimenting, I've found that `chmod`ing the folder 777 fixes this issue.
(see https://github.com/pmarsceill/just-the-docs/pull/170/checks?sha=996a729ffc72b4951f1efd674e6974aefdf3de41)
> Fix linux file permission issues with Gemfile.lock

- ci/go.yml
Set argument `path` for action using `with` as documented.
https://help.github.com/en/articles/workflow-syntax-for-github-actions#jobsjob_idstepswith
> Fix arguments for go-sample workflow in step checkout

- ci/python-package.yml
These core [__flake8__](http://flake8.pycqa.org/en/latest/) tests can quickly find Python syntax errors and undefined names.
__flake8__ avoids the false positives that __pylint__ is so famous for:
* https://lukeplant.me.uk/blog/posts/pylint-false-positives
On the flake8 test selection, this PR does _not_ focus on "_style violations_" (the majority of flake8 error codes that [__psf/black__](https://github.com/psf/black) can autocorrect).  Instead these __tests are focused on runtime safety and correctness__:
* E9 tests are about Python syntax errors usually raised because flake8 can not build an Abstract Syntax Tree (AST).  Often these issues are a sign of unused code or code that has not been ported to Python 3.  These would be compile-time errors in a compiled language but in a dynamic …
> Add "Lint with flake8" step to detect Python syntax errors

- ci/dart.yml
The dart runtime is not installed by default. The action failes with an error.
> Fix dart workflow

- ci/node.js.yml
Ran into an issue using this workflow where our `npm test` step would hang awaiting input, something like
```
...
2019-08-15T20:30:10.3557212Z > react-scripts test --env=jsdom
2019-08-15T20:30:10.3557447Z 
2019-08-15T20:30:13.4856720Z No tests found related to files changed since last commit.
2019-08-15T20:30:13.4857633Z Press `a` to run all tests, or run Jest with `--watchAll`.
2019-08-15T20:30:13.4896414Z 
2019-08-15T20:30:13.4896619Z Watch Usage
2019-08-15T20:30:13.4897107Z  › Press a to run all tests.
2019-08-15T20:30:13.4897681Z  › Press p to filter by a filename regex pattern.
2019-08-15T20:30:13.4898265Z  › Press t to filter by a test name regex pattern.
2019-08-15T20:30:13.4898676Z  › Press q to quit watch mode.
2019-08-15T20:30:13.4898970Z  › Press Enter to trigger a test run. …
```
> Node workflow - force Jest to run in CI-mode

- ci/jekyll.yml
To avoid error "chmod: srv/jekyll: No such file or directory", see https://github.com/VincentTam/beautiful-jekyll/commit/2d0370a1f93818a8a8e19dc364e8906ee76aedd7/checks#step:3:6.
> Used absolute path for '/srv/jekyll'

- ci/properties/python-publish.properties.json
- ci/python-publish.yml
Publishing a Python package directly to [PyPI](https://pypi.org/) when you create a release is a really common use case for CI. I think including this as a starter workflow will be very useful for when GitHub Actions is released to everyone.
> Publish Python package to PyPI workflow

- ci/erlang.yml
[rebar](https://github.com/rebar/rebar) has been deprecated for a few years now and [rebar3](https://github.com/erlang/rebar3) has taken its place.
Since rebar3 no longer has a separate step for fetching dependencies so this step is removed. Common Test is enabled in the test run so it will run all tests.
The Erlang docker image is used instead of ubuntu because ubuntu has no package for rebar3.
> update Erlang workflow to rebar3

- ci/maven.yml
Add the `-B` (batch mode) to the `mvn` command line. In interactive mode maven prints many lines of download progress output filling the console output with thousands of useless lines. 
Ideally the github-actions console would interpret `\r' as carriage return (go back to the beginning of the current line and overwrite it). As long as that is not the case using `-B` should be a good enough alternative.
> maven.yml: add `-B` to the maven command line

- ci/haskell.yml
See #159. This adds https://github.com/actions/setup-haskell to the starter Haskell workflow (otherwise, GHC/Cabal are not installed). It also runs `cabal update` before installing dependencies.
> add setup-haskell action to haskell starter workflow

- automation/label.yml
It was pointed out (https://github.com/actions/labeler/issues/18) that when using the labeler from the starter-workflow, it's not clear that there is more work to do to configure the action.  Add information and link to the action's README.
> Pull Request Labeler: add instructions

- ci/dotnet-core.yml
- ci/properties/asp.net-core.properties.json
- ci/properties/dotnet-core.properties.json
The .NET Core template is not ASP specific.  Change the name to ".NET Core".  Additionally, add language categories matching linguist identifiers so that .NET Core template is recommended.
The following .NET Core projects are not - but should be - using this as the recommended template:
> Rename "ASP.NET Core" to ".NET Core", add language identifiers.

- ci/gradle.yml
`./gradlew` build fails because it does not have execute permissions. Adding the execute permissions using `chmod` fixes this issue.
See [Android: Granting execute permission for gradlew](https://github.com/actions/starter-workflows/pull/70) for more details
> Gradle: Granting execute permission for gradlew

- ci/python-app.yml
The other approach would be __python-version: 3.x__ to allow the tests to run on the latest Python.
Thank you for sending in this pull request. Please make sure you take a look at the [contributing file](CONTRIBUTING.md). Here's a few things for you to consider in this pull request:
> Upgrade from Python 3.7 to 3.8

- ci/docker-push.yml
- ci/properties/docker-push.properties.json
I'm very excited about Docker support in [GitHub Package Registry](https://help.github.com/en/github/managing-packages-with-github-package-registry/configuring-docker-for-use-with-github-package-registry).
I wanted to create a starter workflow for people already using and familiar with Docker Hub's [automated builds](https://docs.docker.com/docker-hub/builds/) and [automated testing](https://docs.docker.com/docker-hub/builds/automated-testing/) workflow.
This PR replicates 3 of the core behaviors.
1. Run docker compose based test suite. Known as ["Autotest"](https://docs.docker.com/docker-hub/builds/automated-testing/) on Docker Hub.
2. Build and publish `master` to `latest` tag. While `master` is a git convention, `latest` is the default tag that's pulled by default.
3. Also build and …
> Add Docker push to GitHub Package Registry

- ci/node.js.yml
Having separate steps makes it easier to determine what failed.
Switching from `npm ci` to `npm install` because the Windows image uses node v8.10.0 and npm v5.6.0. `ci` was introduced in npm v5.7.0.
See https://github.com/actions/virtual-environments/issues/88
> Use separate steps for install, build and test

- ci/properties/npm-publish.properties.json
Quick name change to update a reference to "GitHub Package Registry" to "GitHub Packages".
> GitHub Package Registry is now GitHub Packages

- ci/python-package.yml
We're using this template for the new language guide for Python and @brcrista [mentioned](https://github.com/github/help-docs/pull/11924/files#r360389597) max-parallel option might a carryover from Azure. I think there are only 5 jobs that will get kicked off, so it's a little redundant and I haven't noticed other CI templates using max-parallel.
> Remove max-parallel

- ci/elixir.yml
Now we have a more efficient way to build elixir projects using actions/setup-elixir.
This reduce execution of any build by 10 seconds approximately.
It's important to recommend the use of the actions over docker builds because actions are faster.
> Use actions/setup-elixir

- ci/google.yml
The google.yml deployment workflow starter hardcoded the registry hostname as `gcr.io` even though there are other possible registry hostnames. It also hardcoded the deployment name. This puts them in env variables and adds to the comments that they need to be adjusted by the user.
> Remove hardcoded values from google.yml

- ci/node.js.yml
Node.js 8 went End-of-Life at the end of 2019 (https://github.com/nodejs/Release) and should not be used in new workflows.
> Remove End-of-Life Node.js 8.x

- ci/node.js.yml
Switch back to using `npm ci`, which is more efficient than `npm install`
> Switch back to `npm ci`

- ci/swift.yml
When creating new workflow using Swift, the macOS name is not lowercase. The editor tells you the value is invalid. See for yourself on the following screenshot:
I propose making the virtual machine lowercase so people do not get this warning during Swift package setup.
> Fix macOS virtual machine case in Swift workflow

- ci/python-package.yml
Python 2 is deprecated: https://www.python.org/doc/sunset-python-2/
> Remove Python 2.7 from default tests

- ci/properties/aws.properties.json
- ci/properties/azure.properties.json
- ci/properties/google.properties.json
This PR updates the existing `*.properties.json` files for workflows with `null` `categories` present. All of these workflows indeed should have one or more categories, which have been added.
> Add missing categories

- ci/dotnet-core.yml
2.2 is no longer supported, so moving to latest SDK released for .NET core which supports and encourages LTS runtime version as well as down-level building.
> Updating .NET Core SDK version to LTS

- ci/properties/aws.properties.json
- ci/properties/azure.properties.json
- ci/properties/google.properties.json
Reverts actions/starter-workflows#347
There were some issues with Azure becoming recommended for all workflows while the other partern worklflows are not, this behavior is not desired. Verified this locally
Original thread where this was discussed: https://github.slack.com/archives/CMUS9J5K9/p1582047037027300?thread_ts=1582046679.021400&cid=CMUS9J5K9
See also: https://github.com/github/github/pull/136656#discussion_r385404724
> Revert "Add missing categories"

- ci/npm-publish.yml
The setup-node action will default the scope to the correct user (the repo owner), so we do not need to explicitly include it in the workflow.  Removing it ensures that the starter template is easier for people to use; now there are no changes necessary to get started.  https://github.com/actions/setup-node/blob/master/src/authutil.ts#L26
> npm-publish: remove explicit scope

- ci/gradle-publish.yml
https://help.github.com/en/packages/using-github-packages-with-your-projects-ecosystem/configuring-gradle-for-use-with-github-packages
In the example above, the Gradle code tries to get the token value from the `TOKEN`, yet this workflow saves the token in the `PASSWORD`.
Easy fix yet can save lots of time for newcomers.
> Inconsistent environmental variable name

- ci/docker-publish.yml
https://github.com/Licsber/opencv-docker/runs/514244582?check_suite_focus=true
Push image: 
Error parsing reference: "docker.pkg.github.com/Licsber/opencv-docker/opencv:latest" is not a valid repository/tag: invalid reference format: repository name must be lowercase
My username contains uppercase characters, this make push failed.
So fix the bug by change all uppercase in IMAGE_ID to lowercase.
> Bug fix :  repository name must be lowercase

- ci/azure.yml
This workflow assumes an App Service web app has already been created and that a user knows how to obtain the desired input values. This cannot be assumed. Therefore I have included references to the relevant documentation.
Thank you for sending in this pull request. Please make sure you take a look at the [contributing file](https://github.com/actions/starter-workflows/blob/master/CONTRIBUTING.md). Here's a few things for you to consider in this pull request:
> Adds App Service documentation references

- ci/haskell.yml
Using `cabal install` to install dependency doesn't work at all, because it is a command for installing executables. Updated to use `cabal build`, and made sure that tests and benchmarks will be built.
> ci/haskell.yml: properly build dependencies, tests and benchmarks

- ci/go.yml
setup-go released a v2 recently after being in v2-beta for quite awhile with customer validation.
There are many unit and e2e workflows validating it (along with customer validation).
Here's an example workflow of mine validating it.
https://github.com/bryanmacfarlane/actions-playground/runs/593761737?check_suite_focus=true
I also update it with a `^` which setup-go supports to ensure as 1.14, 1.15 etc are released, we don't have to keep updating the starter workflow.  go will maintain compat across 1.x
> update setup-go to v2

- ci/ruby.yml
This PR adds a starter workflow for [ruby/setup-ruby](https://github.com/ruby/setup-ruby), the most complete action to setup Ruby. This action is hosted in the official GitHub Ruby organization.
I'm doing this PR based on this comment by @ethomson : https://github.com/actions/setup-ruby/pull/49#issuecomment-607416625
- The name of CI workflows should only be the name of the language or platform: for example "Go" (not "Go CI" or "Go Build")
Should it just be `Ruby` here?
But then we would have two starter workflows with the title `Ruby` which seems confusing.
I followed a similar structure to `ci/node.js.yml`, and used the `matrix` form to show how to test on multiple Rubies, including alternative implementations, which …
> Add starter workflow for ruby/setup-ruby

- ci/python-app.yml
- ci/python-package.yml
If there's no requirements.txt then there's no need to `pip install` them.
Fixes #456
> python: gracefully handle no requirements.txt

- ci/node.js.yml
The CI environment variable is now [set by GitHub Actions directly](https://github.blog/changelog/2020-04-15-github-actions-sets-the-ci-environment-variable-to-true/).  No need to set it in the workflow.
> node: remove CI=true environment variable

- ci/php.yml
Composer, PHP dependency manager is about to release version 2. It deprecates the `--no-suggest` flag because the output is now truncated to prevent spamming suggestions. Using `--no-suggest` raises a deprecation notice now:
Please see for changes in Composer v2: https://php.watch/articles/composer-2
This PR removes the `--no-suggest` flag from the `composer install` step.
> PHP: Remove deprectated composer --no-suggest

- ci/docker-publish.yml
The PR tries to fix a behavior of the existing Github Action - "Publish Docker Image"
Current Behavior:
* changing the `IMAGE_NAME` variable breaks the build
Expected Behavior:
* changing the `IMAGE_NAME` variable should not break the build
> fix: use the IMAGE_NAME variable

- ci/python-app.yml
- ci/python-package.yml
- ci/python-publish.yml
The `v2` version of [setup-python](https://github.com/marketplace/actions/setup-python) was recently released.
All the Python starter workflows that currently use `actions/setup-python@v1` should be updated to use  `actions/setup-python@v2`
> Bump setup-python from v1 to v2

- ci/elixir.yml
As now [recommended](https://github.com/actions/setup-elixir/tree/2071beb570a53fb599fbd638d0a4f4577d57143d#usage) in the action's README, the configuration versions should be strings so that YAML parsing doesn't truncate something like `23.0` to `23`, which isn't equivalent.
> Define OTP/Elixir versions as strings

- .github/workflows/validate-data.yaml
Just saw that the job was named the same as the sync one that I "adapted" it from, which meant I wasn't able to select it for a branch protection. This should fix that
> Update workflow job name

- ci/laravel.yml
From the upgrade guide for Composer v2.0:
> Deprecated --no-suggest flag as it is not needed anymore
https://github.com/composer/composer/blob/master/UPGRADE-2.0.md#for-composer-cli-users
> Remove deprecated '--no-suggest' flag

- automation/stale.yml
Let's move the recommended stale cron tab away from 00:00 UTC
> Change the cron for stale

- ci/php.yml
```
```
---
Updates the cache key used in the PHP workflow to use the word `php` instead of `node` since this is a php workflow after all.
> Update php cache key to use php in its name

- ci/elixir.yml
This just changes the name of the "Setup elixir" step to "Set up Elixir". cc https://github.com/actions/setup-elixir/issues/33
> Improve name of "Setup elixir" step in Elixir workflow

- ci/elixir.yml
Source for this being latest Elixir: https://github.com/elixir-lang/elixir/releases
There is an OTP 23.0 (https://www.erlang.org/downloads) but https://hexdocs.pm/elixir/compatibility-and-deprecations.html#compatibility-between-elixir-and-erlang-otp indicates Elixir 1.10 isn't known to be compatible with a later OTP than 22.
> elixir.yml: Specify latest Elixir/OTP versions

- ci/manual.yml
- ci/properties/manual.properties.json
It is not:
---
Thank you for sending in this pull request. Please make sure you take a look at the [contributing file](https://github.com/actions/starter-workflows/blob/master/CONTRIBUTING.md). Here's a few things for you to consider in this pull request.
Please **add to this description** at the bottom :point_down:
```
```
This adds a new workflow template demonstrating the use of the new `workflow_dispatch` event …
> Add manually triggered workflow template

- ci/gem-push.yml
Fixes github/c2c-package-registry#2154
Ruby 2.7 now includes built in support for the `GEM_HOST_API_KEY` env var. When set, this is used in preference to the `--KEY` / `.gem/credentials` option. The `GEM_HOST_API_KEY` option _must_ include a `Bearer` prefix.
When not set, GitHub Packages will fail with:
```
Your request could not be authenticated by the GitHub Packages service. Please ensure your access token is valid and has the appropriate scopes configured.
```
https://github.com/saigkill/publican_creators/runs/853772278?check_suite_focus=true#step:5:17
- Include `Bearer` in `GEM_HOST_API_KEY` env var (for compatibility with 2.7+)
- Use `${{secrets.GITHUB_TOKEN}}` instead of `${{secrets.GPR_AUTH_TOKEN}}`
- Use `${{ github.repository_owner }}` as the default `OWNER`
- Use `ruby-version` …
> Include Bearer in GEM_HOST_API_KEY

- .github/pull_request_template.md
- .github/workflows/sync_ghes.yaml
- CONTRIBUTING.md
- script/sync-ghes/index.ts
This is part of #589 and covers any cases of `master` in this repository, replacing with `main`.
The last couple of references to `master` in this repo are to other repositories.
> Rename to main

- ci/dotnet-core.yml
Blazor projects fail to build in 3.1.101 due to a bug in the .NET Core SDK. Updating the SDK to the latest version (3.1.301) fixes this bug.
> Update .NET Core SDK version

- ci/terraform.yml
It is not:
---
Thank you for sending in this pull request. Please make sure you take a look at the [contributing file](https://github.com/actions/starter-workflows/blob/main/CONTRIBUTING.md). Here's a few things for you to consider in this pull request.
Please **add to this description** at the bottom :point_down:
```
```
> Move "checkout" comment adjacent to its step

- ci/dotnet-core-desktop.yml
Both the [upload-artifact](https://github.com/actions/upload-artifact) and [download-artifact](https://github.com/actions/download-artifact) are on `v2`. Our public documentation also points to `v2` and was recently updated: https://docs.github.com/en/actions/configuring-and-managing-workflows/persisting-workflow-data-using-artifacts
Doing a quick search, I only found one place in our starter workflows that uses the artifact actions. This small PR just bumps up the versions from v1 to v2
> Update artifact actions from v1 to v2

- ci/d.yml
- ci/properties/d.properties.json
- icons/d.svg
Description (and commit message):
```
D is a statically and strongly typed, multi-paradigm, general-purpose native programming language.
D is fully open-source and maintained by a volunteer community.
For more information, see https://dlang.org
This patch adds a minimal workflow that allows users to compile D projects that use DUB,
the official D package manager and build tool.
The workflow uses the community-maintained `setup-dlang` action,
which can install any version of `dmd` (the reference compiler),
or `ldc` (the LLVM-based, performance oriented compiler,
on any of the three platforms currently supported by Github free runners.
Support for GDC is not yet implemented.
The logo used (d.svg) originates from
https://github.com/dlang/dlang.org/blob/master/images/dlogo_2015.svg
and is …
```
> Add D workflow

- .github/pull_request_template.md
- CONTRIBUTING.md
This is an update to the policy around new community starter workflows as mentioned in https://github.com/github/c2c-actions/issues/1216
> updates to starter workflows

- ci/docker-publish.yml
GitHub Container Registry (GHCR) is intended to supersede the Docker service in GitHub Packages. I've updated the Publish Docker template to use GHCR which was released as a public beta on 9/1/20:
- GHCR doesn't support `GITHUB_TOKEN` so a PAT will need to be created and saved as `CR_PAT` instead.
- The URL is ghcr.io instead of docker.pkg.github.com.
- The repo path part is no longer required. You publish to ghcr.io/[org]/[image-name].
> Update Publish Docker template to publish to GitHub Container Registry

- ci/npm-publish.yml
Replace the registry url with a token that will auto-replace, but be the correct URL in an enterprise environment.
> Update to use the $registry-url() token

- ci/pylint.yml
On analyzing the code with `pylint`, the name of the step is `Test with pytest`, which is certainly not what it does.
It is not:
---
**Please note that we are not accepting new starter workflows at this time. Updates to existing starter workflows are fine.**
---
```
```
> Fix on step name for pylint action

- ci/gem-push.yml
Hi thanks for this action!
With GitHub Packages everything is ok, but we had a problem with "bearer" in the RubyGems step.
We solved when we removed the bearer in the ruby gem step.
Is it ok?
Repo with our test (https://github.com/rubynetti/amico-db)
It is not:
---
**Please note that we are not accepting new starter workflows at this time. Updates to existing starter workflows are fine.**
---
```
```
> Fix rubygems step

- ci/cmake.yml
Hi,
it seems docs article link changed.
---
```
```
> Fix docs link in cmake CI file

- ci/azure.yml
For Linux Apps, Developers need to set a new app setting called WEBSITE_WEBDEPLOY_USE_SCM and set to `true` before downloading the publish profile.
> Updating the pre-req configuration steps for Azure workflow

- ci/docker-publish.yml
Reverts actions/starter-workflows#639
We will be making the GitHub Container Registry an opt-in beta, so we want to revert this starter template to use Docker and `GITHUB_TOKEN`.
> Revert "Update Publish Docker template to publish to GitHub Container Registry"

- README.md
python-django.* has renamed to django.*, while the doc remains the same
> remove misleading info

- code-scanning/codeql.yml
- code-scanning/properties/codeql.properties.json
This PR adds a workflow template for Code Scanning. In the first instance this will only be shown on the setup page for Code Scanning.
> add codeql workflow

- ci/python-package.yml
`pip` was called in two different ways which is a bit inconsistent, this change just makes it so that it is called in the same way both times.
> Use consistent calls to pip

- ci/npm-publish.yml
It was `npm_token` before, but for GitHub it's `GITHUB_TOKEN`. This makes them be the same, all-cap case.
> Make NPM_TOKEN consistent with GITHUB_TOKEN

- ci/maven.yml
Changes:
- Write out `-B` as `--batch-mode` to make it easier to understand or searchable by users not familiar with all Maven command line options
- Remove `--file pom.xml` because it is the default anyways. Or does it exist to indicate how users could specify a different file?
- Add `--update-snapshots` to force update snapshots (otherwise it might use stale versions), see [this StackOverflow question asking about the behavior](https://stackoverflow.com/questions/29020716). Note that this overwrites locally installed packages, but should probably not be an issue for the great majority of projects.
- Run all phases up to including `verify` (instead of `package` only) to also run integration tests
Note that [GitHub Help: Building and testing Java with …
> Improve maven.yml

- ci/openshift.yml
- ci/properties/openshift.properties.json
It is not:
---
---
- [] Packaging workflows should run on `release` with `types: [ created ]`.
```
```
> Update OpenShift starter with new actions

- ci/node.js.yml
Documentation of upstream version support: https://nodejs.org/en/about/releases/
This PR adds support for Node.js 15.x because it is supported upstream.
Documentation is also added in code to support this change and ease further changes in the future as needed.
---
Follow-on work
- For people using our CI workflows, we always want to recommend they test including the latest upstream-supported language versions. This type of PR I'm making here can be automated. The easiest way is to compare the upstream languages' list of supported versions against the hardcoded language versions in this repository using CI and produce errors when not included.
> Add every version of Node.js that is supported upstream

- ci/django.yml
- ci/python-app.yml
- ci/python-package.yml
adding latest python 3.9 into the bootstrap script. 
---
relates to https://www.python.org/downloads/release/python-390/ (`Release Date: Oct. 5, 2020`)
> python: include python 3.9 for the build

- ci/haskell.yml
keep using the latest haskell offerings when bootstrapping the action scripts.
> haskell: ghc 8.10 and cabal 3.2

- ci/d.yml
This fixes the previous version using the outdated `::set-env` command which is disabled now. (See https://github.com/dlang-community/setup-dlang/issues/34)
Commit is of https://github.com/dlang-community/setup-dlang/releases/tag/v1.0.3
> update setup-dlang to v1.0.3

- ci/ruby.yml
https://github.com/ruby/setup-ruby/releases/tag/v1.61.0
Is it allowed to just use `uses: ruby/setup-ruby@v1` instead of a full sha nowadays in starter-workflows? (it seems so from the text below)
That seems much better.
---
```
```
> Update ruby.yml to use the latest release of ruby/setup-ruby

- ci/ruby.yml
ruby: add ruby 2.7 and 3.0 into bootstrap script
---
relates to https://www.ruby-lang.org/en/news/2020/12/25/ruby-3-0-0-released/
> ruby: add ruby 2.7 and 3.0 into bootstrap script

- ci/go.yml
update starter workflow
---
go 1.16 would [use go modules build by default](https://tip.golang.org/doc/go1.16#modules), so it is good for new projects to use without dep (also `dep` project was [archived last year](https://github.com/golang/dep/commit/f13583b555deaa6742f141a9c1185af947720d60)).
> go: update starter

- ci/dotnet-desktop.yml
- ci/dotnet.yml
Fixes #619 
Originally fixed by #620 
This version was updated to .NET 5
> dotnet-Workflows: Use latest channel version

- .github/pull_request_template.md
Proposes tune-ups to the existing PR template. The intent is to clarify requirements for proposing new starter workflows, with a shared section for common requirements, and dedicated sections for each "flavor" of workflow (CI, code scanning, ...).
For new Code Scanning starter workflows, we are requesting membership in our recently relaunched Partner Program.
> Clarify pre-requisites, tasks for onboarding of new starter workflows

- ci/php.yml
Composer maintainer here. 
I would recommend running validate in strict mode by default, as it makes it exit with a non-zero code when there is a warning. By default warnings are not treated as fatal and as such the process still returns 0, but in CI that often means stuff gets missed.
> Make the validation strict by default

- ci/php.yml
Composer install should always run IMO, it is the safer way to do this. A few reasons:
- As part of install some scripts may run which do things in directories outside of the cached vendor dir
- Some projects use composer plugins which install packages outside the vendor dir, which means those will not be cached even tho the cache was a hit, so running install always makes sure anything missing will get installed correctly.
- It runs very quickly (<1s) if there is nothing to change, so it's a fairly harmless default IMO, which might save some head-scratching.
> Always run composer install even if the vendor dir was restored

- ci/elixir.yml
[actions/setup-elixir](https://github.com/actions/setup-elixir) is no longer maintained and now suggests using [erlef/setup-elixir](github.com/erlef/setup-elixir)
This should be updated to help new Github Actions users to use the supported action.
> actions/setup-elixir now lives under erlef GH Org

- ci/alibabacloud.yml
- ci/aws.yml
- ci/ibm.yml
- ci/openshift.yml
- ci/tencent.yml
- ci/terraform.yml
Updates the following partner starter workflows to take advantage of [`environment`s](https://docs.github.com/en/actions/reference/environments), which allow for features like [protection rules](https://docs.github.com/en/actions/reference/environments#environment-protection-rules) and [environment secrets](https://docs.github.com/en/actions/reference/environments#environment-secrets).
- Alibaba
- AWS
- IBM
- OpenShift
- Tencent
- Terraform
Prior art: [Azure](https://github.com/actions/starter-workflows/pull/784), [Google](https://github.com/actions/starter-workflows/pull/807)
> Add environment: production to partner starter workflows

- CONTRIBUTING.md
The wording in the pull request template was changed from recommend to require in https://github.com/actions/starter-workflows/pull/806,
but the same change was not made to the README.
> Fix wording in README to follow pull request template

- ci/php.yml
Hello!
`php.yml` CI workflow starts Composer with the deprecated `--no-suggest` option.
It was fixed in #490 and hasn't been reverted as far as I can see, but the current version of the workflow contains this deprecated option for some strange reason.
Let's try to remove it again!
> Remove the deprecated "--no-suggest" option from the Composer install step

- .github/workflows/sync_ghes.yaml
- .github/workflows/validate-data.yaml
- ci/azure.yml
- ci/node.js.yml
- ci/npm-publish.yml
Since actions/setup-node v2 has been declared stable since [v2.1.4](https://github.com/actions/setup-node/releases/tag/v2.1.4) (released on 2020-12-16), it should be safe to move everyone to v2.
> Use actions/setup-node v2

- ci/jekyll.yml
* Add _recursive_ write permissions to `/srv/jekyll` in jekyll starter workflow
Fixes issues where the current version produced `permission denied` errors when jekyll needs to create the output directory during build in a private repository.
> Add recursive write permissions to site directory in jekyll starter workflow

- code-scanning/tfsec.yml
The tfsec action doesn't require the GitHub token so removing it
---
---
```
```
> tfsec: Remove the github token

- ci/python-package.yml
Because the whole purpose of this worflow is to see on which Python the package fails (if it fails), and with `fail-fast` it leads to unnecessary re-runs.
> Do not use fail-fast when testing multiple Pythons

- ci/openshift.yml
As [oc-new-app](https://github.com/redhat-actions/oc-new-app) action now has `port` as an optional input so now it's not necessary to have port in the workflow.
also, many users will not have `8080` as the default port to expose, so for them it may break if somehow they miss to update the port value.
Removing the default value from port env will avoid this kind of mistake.
Signed-off-by: divyansh42 <diagrawa@redhat.com>
---
---
```
```
cc @tetchel
> Remove default value of env `APP_PORT`

- ci/docker-publish.yml
The changes in this PR update the `docker-publish` workflow in a few ways:
* It now supports logging in and pushing images to the [GH Container Registry](https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-container-registry)
* Instead of using error-prone shell scripts to extract metadata and build/push images it's using Docker actions
* The registry being used is now defined in a variable
* I'm a GitHub employee so I'm assuming that doesn't apply to me 
```
```
> Update push docker container to support container registry

- ci/python-publish.yml
---
---
- **Not Applicable**
- **See summary below describing alternative release types**
- **Not Applicable**
```
```
The [Python Packaging Authority](https://www.pypa.io/en/latest/) (PyPA)--the working group responsible for `pip` and `PyPI`, among other packaging tools--maintains an action for uploading Python packages to PyPI.
This PR makes the following changes to the `python-publish` example:
1. Use the PyPA-maintained PyPI upload action instead of directly interacting with `twine`.
1. Uses [`build`](https://pypa-build.readthedocs.io/en/latest/) to generate the sdist & wheel that will be uploaded to PyPI instead of setuptools, as the former is …
> Update Python package build and upload example

- .github/workflows/stale.yml
- automation/stale.yml
We have a set of cron helpers to allow start workflows to specify an hourly, daily, or weekly schedule without setting a specific time. These are replaced with a randomized schedule when the starter workflow is selected by a user.
> Use `$cron-daily` for daily schedules

- ci/ios.yml
There was a mistake in [last commit](https://github.com/actions/starter-workflows/commit/5ac32fc0977190a464c62c63cad5fcb04067c34e),  that added additional *`* which causes this error 
```
/Users/runner/work/_temp/2259bec8-2d05-441b-ada0-fad594134af2.sh: line 5: unexpected EOF while looking for matching ``'
14
Error: Process completed with exit code 2.
```
I just simply removed it.
---
---
```
```
> Removed *`* because it crashes build

- ci/npm-publish.yml
node v12 is in maintenance mode
node v16 (next TLS) is not ready yet
---
```
```
> npm-publish: update to use the latest TLS v14

- ci/ios.yml
Removes the extra ` character from this command. 
Another line was already fixed in #935. This is the same change as #1016, but that PR was closed.
> Remove extra character

- ci/deno.yml
Based on #1006, this removes the matrix to simplify the template and fix the deno fmt issue on Windows with actions/checkout as outlined in #1006.
> The actions/checkout action on windows checks out files with \r\n line endings instead of preserving them. This causes deno fmt --check to fail because the line endings are \r\n instead of \n.
> Remove matrix for Deno template

- ci/properties/node.js.properties.json
The purpose of this PR is to be bubble up the `node.js` template for `Vue` based templates. `Vue` today is being detected by [linguist].(https://github.com/github/linguist/blob/971e152fabca12e0ad386833eecb7b15e312a09f/lib/linguist/languages.yml#L6438)
Using `npm` commands for build makes sure we take no global dependencies, and everything defined in `scripts` from `package.json` gets executed. (_Source_: https://stackoverflow.com/questions/42936588/which-command-do-i-use-to-generate-the-build-of-a-vue-app)
> add `Vue` to nodejs props

- deployments/aws.yml
In updating the deployment guides, it felt clearer to make all user-set values be environment variables that the user can set at the top of the workflow file. (Similar to the [azure](https://github.com/actions/starter-workflows/blob/main/deployments/azure.yml) and [GKE](https://github.com/actions/starter-workflows/blob/main/deployments/google.yml) workflows.) The docs use this format in the [example workflow](https://docs.github.com/en/actions/deployment/deploying-to-amazon-elastic-container-service). This PR updates the AWS starter workflow to use the same strategy so that the starter workflow and corresponding docs align.
---
---
```
```
> use env variables for user-set values

- ci/npm-publish-github-packages.yml
- ci/properties/npm-publish-github-packages.properties.json
- ci/properties/npm-publish.properties.json
Currently we suggest that folks dual publish to both npm + gpr.
There are a large number of edge cases related to doing this and IMHO it is
not the best practice. Let's make two separate workflows.
> chore: split npm publish into 2 workflows

- deployments/azure-webapps-node.yml
---
Node 10 isn't even in maintenance mode any more! I should have caught this sooner. 
https://nodejs.org/en/about/releases/
> Use Node 14 in the starter workflow, not Node 10

- ci/docker-publish.yml
This change installs `sigstore/cosign` using the `cosign-installer` action,
and uses sigstore's "keyless" signing process to sign the resulting image
digest using the action's identity token (see: `id-token: write`).
Signed-off-by: Matt Moore <mattomata@gmail.com>
---
```
```
> Have the starter `docker-publish` action sign digests.

- ci/docker-publish.yml
Now that cosign 1.4 is out, we can perform keyless signing without panicking on private images (and without `--force` uploading to Rekor).
For private repos, signing will occur, but without `--force` it emits a warning like this:
Signed-off-by: Matt Moore <mattmoor@chainguard.dev>
---
---
```
```
> Enable keyless signing for private Docker repos.

- ci/android.yml
- ci/ant.yml
- ci/gradle-publish.yml
- ci/gradle.yml
- ci/maven-publish.yml
- ci/maven.yml
- ci/scala.yml
The jdk distribution adoptopenjdk (adopt) is rebranded into eclipse adoptium (temurin), see https://blog.adoptopenjdk.net/2021/03/transition-to-eclipse-an-update/
If im not mistaken, I dont need to apply to the Github Technology Partner as this is only an update to existing workflows. I also think that most of the checkbox probably doesnt apply to this PR. 
Let me know if I should change something.
- [N/A] Prior to submitting a new workflow, please apply to join the GitHub Technology Partner Program: [partner.github.com/apply](https://partner.github.com/apply?partnershipType=Technology+Partner).
---
---
```
```
> Switch java distribution from 'adopt' to 'temurin'

- .github/pull_request_template.md
Updating PR template to include a check for specifying appropriate permissions for `GITHUB_TOKEN`.
Thanks to @varunsh-coder for calling [this](https://github.com/actions/starter-workflows/issues/1299) out.
> Add check for GITHUB_TOKEN permissions

- ci/deno.yml
The version of the `denoland/setup-deno` action is a wierd hash that doesn't work. Instead using `v1` from the marketplace listing seems to work.
> Fix version of `denoland/setup-deno`

- ci/gradle-publish.yml
- ci/gradle.yml
Updates starter workflows using `gradle-build-action` to the latest v2.1.2 release.
> Update for `gradle-build-action@v2.1.2` release

- code-scanning/properties/detekt.properties.json
- script/sync-ghes/index.ts
This allows manually excluding starter workflows from being bundled into an Enterprise Server release and removes a workflow that was mistakenly.
A lot of starter workflows won't work on Enterprise Server without specific tweaks to ensure it will work on self-hosted runners and if the runner is air-gapped. These starter workflows are currently detected based on the Actions they use, but in some cases there are workflows that don't include any Actions but use shell scripts to make outbound calls that might fail in an Enterprise Server environment.
In these cases it's useful to be able to manually specify that a workflow shouldn't be included in Enterprise Server. This adds the ability to do that.
> Fix some workflows not being excluded from Enterprise syncing.

- ci/dotnet-desktop.yml
- code-scanning/msvc.yml
- code-scanning/xanitizer.yml
- deployments/azure-webapps-dotnet-core.yml
- deployments/azure-webapps-java-jar.yml
- deployments/azure-webapps-node.yml
- deployments/azure-webapps-php.yml
- deployments/azure-webapps-python.yml
The first-party GitHub actions `actions/upload-artifact` (([link](https://github.com/actions/upload-artifact)) and `actions/download-artifact` ([link](https://github.com/actions/download-artifact)) have had a major version bump. Updating the versions here.
> Update `download-artifact` and `upload-artifact` from `v2` to `v3`

- ci/gradle-publish.yml
- ci/gradle.yml
This PR updates the SHA for gradle/gradle-build-action to point to the v2.1.4 release.
No other workflow changes are included.
---
---
```
```
> Update to v2.1.4 of gradle-build-action

- CODEOWNERS
Actions team is the primary reviewer for code-scanning starter workflows as well.
> Add Actions team as CODEOWNERS for code-scanning starter workflows

- ci/properties/rubyonrails.properties.json
The workflows for Ruby, RubyGem, Jekyll, and similar are all just the name of the language, package, or framework. This name change brings Rails in line with the other starters.
> Shorten Rails workflow name, in line with others

- code-scanning/codeql.yml
git.io is deprecated.
Replace the references with full links or aka.ms links to the same documentation.
- [N/A] Prior to submitting a new workflow, please apply to join the GitHub Technology Partner Program: [partner.github.com/apply](https://partner.github.com/apply?partnershipType=Technology+Partner).
---
---
```
```
> CodeQL starter workflow: Replace git.io links

- code-scanning/dependency-review.yml
This PR fixes a typo in the Dependency Review Action YML install. It was first reported in https://github.com/actions/dependency-review-action/issues/44#issuecomment-1126774600.
> Fixing typo in dependency-review-action

- .github/pull_request_template.md
Changed https://github.com/actions/starter-workflows/tree/main/ci to https://github.com/actions/starter-workflows/tree/main/code-scanning
> Fix link to `code-scanning` directory

- deployments/azure-kubernetes-service-kompose.yml
Trigger spec is missing from AKS kompose starter workflow and that even shows up as error in the workflow editor.
> Fix the missing `on` trigger for AKS Kompose

- code-scanning/crda.yml
- code-scanning/properties/crda.properties.json
- deployments/openshift.yml
- Add CRDA scan starter workflow in the **code-scanning** section.
- Modify existing OpenShift starter workflow to trigger CRDA workflow.
Signed-off-by: divyansh42 <diagrawa@redhat.com>
---
---
```
```
> Add CRDA starter workflow and modify openshift workflow

- .github/workflows/auto-assign.yml
Fixes PR auto assign by changing trigger on `pull_request` to `pull_request_target` so that explicit approval is not needed for workflow to run.
> Fix PR auto assign

- script/sync-ghes/settings.json
Adding pages to ghes sync script to prevent unknown addition to ghes and keep it up-to-date
> Add pages to ghes sync script

- script/sync-ghes/settings.json
`actions/setup-python` is part of ghes. So making it enabled in sync ghes script to allow actions using only that to be part of GHES
> Add setup-python to list of enabledActions for ghes

- code-scanning/apisec-scan.yml
- code-scanning/brakeman.yml
- code-scanning/checkmarx.yml
- code-scanning/clj-holmes.yml
- code-scanning/clj-watson.yml
- code-scanning/codacy.yml
- code-scanning/codescan.yml
- code-scanning/contrast-scan.yml
- code-scanning/eslint.yml
- code-scanning/hadolint.yml
- code-scanning/lintr.yml
- code-scanning/mobsf.yml
- code-scanning/msvc.yml
- code-scanning/njsscan.yml
- code-scanning/ossar.yml
- code-scanning/phpmd.yml
- code-scanning/pmd.yml
- code-scanning/powershell.yml
- code-scanning/prisma.yml
- code-scanning/puppet-lint.yml
- code-scanning/rust-clippy.yml
- code-scanning/semgrep.yml
- code-scanning/snyk-container.yml
- code-scanning/snyk-infrastructure.yml
- code-scanning/sobelow.yml
- code-scanning/sysdig-scan.yml
- code-scanning/trivy.yml
- code-scanning/veracode.yml
- code-scanning/xanitizer.yml
This is a fix for any starter workflow that is using the `github/codeql-action/upload-sarif` action that is [overriding the default GITHUB_TOKEN permissions](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token) and NOT explicitly including `actions: read`.  
This is documented as a required permission in the [Example workflow for SARIF files generated outside of a repository](https://docs.github.com/en/code-security/code-scanning/integrating-with-code-scanning/uploading-a-sarif-file-to-github#example-workflow-for-sarif-files-generated-outside-of-a-repository). 
- workflows have already been fixed. (ex: https://github.com/actions/starter-workflows/pull/1589)
Currently, these actions will fail (with 403) for a private repository …
> Starter Workflows Failing on Private Repositories - add actions: read permission when using upload-sarif

- code-scanning/codeql.yml
Code Scanning can accept multiple uploads for the same tool and uses the concept of category to keep results separated. If not provided explicitly, the category is computed based on a few parameters like workflow path and matrix variables. The implicit computation of the category can create confusion if users change their workflow, as we start considering the new analyses as unrelated to existing results.
By making the category explicit in the workflow we hope to make the concept more prominent and reduce accidental changes.
https://docs.github.com/en/code-security/code-scanning/automatically-scanning-your-code-for-vulnerabilities-and-errors/configuring-code-scanning#configuring-a-category-for-the-analysis
This is updating an existing workflow file.
> Update CodeQL to include category by default

- code-scanning/properties/eslint.properties.json
👋 Hi! I'm from the GitHub Code Scanning team.
We've noticed that ESLint is being incorrectly displayed on GHES.
This change should hide the workflow. 🙇
> Hide ESLint on GHES

- code-scanning/properties/codeql.properties.json
- script/sync-ghes/index.ts
This should stop workflows appearing on GHES when they have not explicitly been vetted as suitable.
> Make enterprise opt-in instead of opt-out

- .github/workflows/sync-ghes.yaml
I think this bug snuck in when [updating all the template workflows to use `$default_branch`](https://github.com/actions/starter-workflows/pull/1724).
> fix trigger for ghes sync

- code-scanning/scorecards.yml
This is removing the trailing spaces in the main YML config file for OpenSSF Scorecards. The trailing spaces can be caught in linters, so it will help developers not having to make an additional commit to fix it.
> Update OpenSSF Scorecard workflow: Remove trailing whitespaces

- ci/deno.yml
This updates the version of the denoland/setup-deno action used in ci/deno.yml starter workflow to a version that uses node16, to remove the warning about node12 workflows being deprecated.
The version updated to is the latest released version, v1.1.1: https://github.com/denoland/setup-deno/releases/tag/v1.1.1
> Update denoland/setup-deno workflow

- deployments/aws.yml
see https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
> update deprecated syntax

- pages/astro.yml
The Pages starter workflow for Astro currently detects various package managers (`npm` vs. `yarn`) but then just uses `npm` in either case. 😓 
Let's correct that to use the detected package manager! 🔍 
---
---
```
```
> Astro: Update to use the detected package manager

- pages/astro.yml
Instead of adding internal support for Astro into the `actions/configure-pages` Action, we can instead just utilize the Astro CLI directly and pass in the desired configuration properties at build time.
Closes https://github.com/actions/starter-workflows/pull/1829
Closes https://github.com/actions/configure-pages/pull/39
---
---
```
```
> Pages: Configure Astro origin and base path using CLI arguments

- script/sync-ghes/index.ts
This fixes a bug in https://github.com/actions/starter-workflows/pull/1759 where it would not correctly filter out workflows in the code-scanning directory because it was being compared against a relative path.
Not sure how I originally managed to make the script work. 😞 
Looks like I need this PR to merge first https://github.com/actions/starter-workflows/pull/1844 with a linter fix.
> Fix code-scanning filtering for relative paths

- code-scanning/properties/codeql.properties.json
This updates the list of supported languages for CodeQL to include Kotlin, as Kotlin for CodeQL [is now in public beta](https://github.blog/changelog/2022-11-28-codeql-code-scanning-launches-kotlin-analysis-support-beta/).
> Add Kotlin to CodeQL supported languages.

- ci/ruby.yml
- ci/rubyonrails.yml
- code-scanning/brakeman.yml
- code-scanning/puppet-lint.yml
- code-scanning/rubocop.yml
- pages/jekyll.yml
Hey! I'm a maintainer for a Jekyll theme ([just-the-docs](https://github.com/just-the-docs/just-the-docs)). We suggest users to use the starter workflow in this repo; however, someone has correctly pointed out that the current pinned version for `ruby/setup-ruby`, v1.115.3, emits a deprecation warning.
The maintainers for `ruby/setup-ruby` responded to this in https://github.com/ruby/setup-ruby/issues/385 and released a fix in [v1.118](https://github.com/ruby/setup-ruby/releases/tag/v1.118.0). At the minimum, I think we should update the example in this repository so that users don't encounter this problem; I've also took the liberty of updating it to the latest version, but happy to revert to 118 if we'd prefer.
Some metadata about the `ruby/setup-ruby` update:
- latest commit version: …
> Update all pinned versions of `ruby/setup-ruby` to latest

- code-scanning/scorecard.yml
Update scorecard.yml with latest releases for ossf/scorecard-action & github/codeql-action/upload-sarif
Noticed these were out-of-date when I saw the below warning on a recent run ([ref](https://github.com/ChrisCarini/automatic-github-issue-navigation-configuration-jetbrains-plugin/actions/runs/4190143423/jobs/7263241173)):
> Update scorecard.yml with latest releases

- pages/mdbook.yml
Trims whitespace on pages/mdbook.yml, which raises linter errors.
> Trim whitespace on pages/mdbook.yml

- pages/jekyll.yml
This PR updates Jekyll workflow to ruby 3.1 to address potential bundle installation issues for jekyll-sass-converter 3.x.
https://jekyllrb.com/news/2022/12/21/jekyll-sass-converter-3.0-released/
Jekyll Sass Converter 3.0 has a minimum rubygems/bundler version requirement which the default rubygems in ruby 3.0 does not meet. While we can use setup-ruby action to update rubygems, ruby >=3.1.3 have the rubygems version that meets the requirement out of box.
> Update jekyll workflow to use ruby 3.1

- pages/astro.yml
- pages/gatsby.yml
- pages/hugo.yml
- pages/jekyll-gh-pages.yml
- pages/jekyll.yml
- pages/mdbook.yml
- pages/nextjs.yml
- pages/nuxtjs.yml
- pages/static.yml
We recently released the next major version of the Pages deployment Action: `actions/deploy-pages@v2`.
This major version utilizes new GitHub REST APIs.
:warning: It may be important to note that these new REST APIs are _NOT_ present in GitHub Enterprise Server yet, but should make it into the next release [of GHES] as well. If that is a risk, it is fine to delay merging this PR until later since `actions/deploy-pages@v1` will continue to function just fine. 👌🏻  
Related:
- https://github.com/actions/deploy-pages/issues/137#issuecomment-1474068155
---
---
```
```
> Update all Pages starter workflows to use actions/deploy-pages@v2

- ci/ruby.yml
- ci/rubyonrails.yml
- code-scanning/brakeman.yml
- code-scanning/puppet-lint.yml
- code-scanning/rubocop.yml
- pages/jekyll.yml
This PR updates https://github.com/ruby/setup-ruby to the current latest version so that users would get latest patch release that contains the bug fix for CVE-2023-28755 and CVE-2023-28756.
Given the use case here the risk is relatively low, but it is still a good idea to get it patched.
> Update ruby/setup-ruby for CVE-2023-28755 and CVE-2023-28756

- code-scanning/bearer.yml
When issues are found the exit code is non zero and so the github action aborts before uploading the sarif report.
This mistake was masked previously due to a bug that was fixed where exit code was not set for this type of report.
> fix: bearer does not upload sarif report

- pages/astro.yml
- pages/gatsby.yml
- pages/hugo.yml
- pages/jekyll-gh-pages.yml
- pages/jekyll.yml
- pages/mdbook.yml
- pages/nextjs.yml
- pages/nuxtjs.yml
- pages/static.yml
Primarily updating Actions usage in Pages starter workflows to be using Node 20.x compatible versions.
Also update to the latest versions of Ruby, mdBook, and Hugo (cc @jmooring).
- Closes https://github.com/actions/starter-workflows/pull/2189
- Closes https://github.com/actions/starter-workflows/pull/2131
> Pages: Update core actions usage and target Node 20

- CODEOWNERS
I'm hoping that a more specific `CODEOWNERS` rule will fix ownership so Code Scanning won't be pinged for review on PRs like https://github.com/actions/starter-workflows/pull/2297 in future.
> Code Scanning shouldn't own `dependency-review.yml`

- ci/gradle-publish.yml
- ci/gradle.yml
- Bump version hashes to use `gradle/actions/setup-gradle@v3.1.0`
- Bump version hash to use `gradle/actions/dependency-submission@v3.1.0`
> Update for `gradle/actions@v3.1.0` release

- code-scanning/codeql.yml
This is updating the CodeQL template to use the new `build-mode` option in the action.
---
---
- [x Should be named _only_ by the name of the language or platform (for example, "Go", not "Go CI" or "Go Build").
```
```
> Code Scanning Update codeql.yml with new build-mode

- script/sync-ghes/index.ts
- script/sync-ghes/settings.json
A read-only synced folder is a folder that:
- Has workflows shipped to GHES
- BUT should not be touched by the sync process
Icons associated with a read-only folder should still stay on the `ghes` branch.
**More context:**  
In PRs:
- https://github.com/actions/starter-workflows/pull/2366
- https://github.com/actions/starter-workflows/pull/2376
- https://github.com/actions/starter-workflows/pull/2387
In English:
> Pages' starter workflows on the `main` branch are not compatible with GHES anymore until artifacts v4 makes it there. We have attempted various way to work around the GHES sync in this repo (what keep in sync the starter workflow between the `main` and `ghes` branch for GHES). The current state is "ok-ish", as in, [our icons have …
> Add the concept of a "read-only" synced folder

- ci/docker-publish.yml
The existing docker-publish workflow has stopped working due to issues with the signing implementation. I noticed this in my personal workflow [here]( https://github.com/jhutchings1/transcode-dvr-recordings/actions/runs/9305924653). It was resolved by updating cosign-installer, and the version of cosign used [here](https://github.com/jhutchings1/transcode-dvr-recordings/actions/runs/9306007317).
> Update cosign versions in Docker-publish

- ci/gradle-publish.yml
- ci/gradle.yml
- Bump version hashes to use `gradle/actions/setup-gradle@v3.4.2`
- Bump version hash to use `gradle/actions/dependency-submission@v3.4.2`
> Update for gradle/actions@v3.4.2 release

- ci/datadog-synthetics.yml
This PR updates the Datadog/synthetics-ci-github-action workflow version to v1.4.0.
The release can be found here: https://github.com/DataDog/synthetics-ci-github-action/releases/tag/v1.4.0
> Update DataDog/synthetics-ci-github-action workflow

- .github/workflows/stale.yml
Having old PRs be closed when no one is looking at them isn't a good experience. I'm changing the stale workflow to be `workflow_dispatch` only so PRs aren't auto-closed
> Update stale.yml to only use workflow_dispatch

- code-scanning/appknox.yml
- code-scanning/properties/appknox.properties.json
---
---
- [x ] Should use sentence case for the names of workflows and steps (for example, "Run tests").
```
```
> Making workflow public. Removing preview label

- code-scanning/jfrog-sast.yml
- code-scanning/properties/jfrog-sast.properties.json
> Add jfrog-sast flow
